/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wangyin.spark;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * You can define enums, which are just 32 bit integers. Values are optional
 * and start at 1 if not supplied, C style again.
 */
public enum MLType implements org.apache.thrift.TEnum {
  CLASSIFICATION(1),
  CLUSTERING(2),
  REGRESSION(3),
  RECOMMENDATION(4);

  private final int value;

  private MLType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MLType findByValue(int value) { 
    switch (value) {
      case 1:
        return CLASSIFICATION;
      case 2:
        return CLUSTERING;
      case 3:
        return REGRESSION;
      case 4:
        return RECOMMENDATION;
      default:
        return null;
    }
  }
}
